version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
      major:
        update-types:
          - "major"
    ignore:
      - dependency-name: "@types/node"
        versions:
          - "24.x"
